### ISSUE TITLE
Fix edge tagged edge builds

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/core#81]
`placeos/edge` builds against master are currently failing to build in codefresh.

**Comment by viv-4** [comment]
The resolution was to remove quoted from the codefresh build argument definition
```
    build_arguments:
      - TARGET=${{EXTRA_TARGET}}
```
Instead of
```
    build_arguments:
      - TARGET='${{EXTRA_TARGET}}'
```

Testing locally I noticed the error is slightly different if I change the edge target in shard.yml to something else, no quotes around `edge`:
`Error target edge was not found in shard.yml.`

Compared to Codefresh:
`Error target 'edge' was not found in shard.yml.`

Setting the `docker build --build-arg` to `'edge'` works fine locally, however removing them in the codefresh definition solved it.
